# -*- coding: utf-8 -*-
"""Bollywood game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BOmSfBSviQ40W7Nw1-hJXzwLCZFt_oDy
"""

import random
guess_list = [
'hera pheri',
'RRR',
'rocky or rani',
'tiger zinda hai',
'pushpa',
'bahubali',
'kabir singh',
]

print('WELCOME TO BOLLYWOOD GAME\n')
cc = random.choice(guess_list).upper()
guesses = len(cc)+4
repw = ['_' for i in range(len(cc))]
while guesses > 0:
    print(f'WORD: {" ".join(repw)}')
    ug = input('Guess a letter:').upper()
    for char in range(len(cc)):
        if ug==cc[char]:
            repw[char]=ug
    if repw.count('_')==0:
        print(f'WORD: {" ".join(repw)}')
        break
    print('Tries remain:',guesses-1,'\n')
    guesses-=1


print('\nYou WIN🎉\n') if repw.count('_')==0 else print('\nYou LOSE💔')